version: '3.3'
services:
# docker run -p 16379:6379 -d --name redis-server redis:6.0 redis-server
  redis:
    container_name: redis-server-6
    image: redis:6.0
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - microservicesnet
networks:
  microservicesnet:
    driver: bridge